server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    port: 25
    username: jurzis@163.com
    password: WIZUXAUEHNPXLOPW
  redis:
    host: 127.0.0.1
    port: 6379
    ###密码windows
    password: 123456
    connect-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.ziyi.entity

logging:
  level:
    org:
      springframework:
        web: trace
    com:
      ziyi:
        mapper: debug

ziyi:
  # 名称
  name: ziyi
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2021
  # 实例开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ziyi/uploadPath，Linux配置 /home/ziyi/uploadPath）
  #profile: D:/ziyi/uploadPath
  profile: /Users/zhy/workspace/my/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

thread-pool:
  default:
    core-pool-size: 50
    max-pool-size: 100
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: thread-

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group
