server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.ziyi.entity

logging:
  level:
    com:
      ziyi:
        mapper: debug