server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    port: 25
    username: jurzis@163.com
    password: WIZUXAUEHNPXLOPW

mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.ziyi.entity

logging:
  level:
    com:
      ziyi:
        mapper: debug

ziyi:
  # 名称
  name: ziyi
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2021
  # 实例开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ziyi/uploadPath，Linux配置 /home/ziyi/uploadPath）
  profile: D:/ziyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
